apiVersion: v1
kind: ResourceQuota
metadata:
  name: metrics-server
  namespace: monitoring
spec:
  hard:
    pods: 4
  scopeSelector:
    matchExpressions:
    - operator: In
      scopeName: PriorityClass
      values:
      - system-cluster-critical